version: '3.1'

services:
 
 php:
  build:
    context: php
  # restart: always
  ports:
    - 8099:80

#  mysql:
#   image: mysql:8.0.13
#   command: --default-authentication-plugin=mysql_native_password
#   environment: 
#    MYSQL_DATABASE: wordpress
#    MYSQL_ROOT_PASSWORD: root
#   volumes:
#    - /Users/macbookpro/Desktop/docker/mysql-data:/var/lib/mysql 
